name: Rider Code Style Check

on:
  workflow_dispatch:  # ручной запуск по кнопке в GitHub Actions

jobs:
  rider-style-check:
    runs-on: self-hosted  # твой self-hosted Mac агент

    env:
      PROJECT_PATH: static-analysis-project  # папка проекта внутри репозитория
      PROJECT_SOLUTION: static-analysis-ci.sln # имя .sln файла проекта
      INSPECTCODE_PATH: /Users/atarasov/resharper-cli/inspectcode.sh

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0.x'
    
    - name: Check if solution exists
      run: |
        if [ ! -f "${{ github.workspace }}/${{ env.PROJECT_SOLUTION }}" ]; then
          echo "❌ Solution file not found: ${{ github.workspace }}/${{ env.PROJECT_PATH }}/${{ env.PROJECT_SOLUTION }}"
          exit 1
        fi

    - name: Run Rider InspectCode
      run: |
        "${{ env.INSPECTCODE_PATH }}" \
          --profile="${{ github.workspace }}/hitapps_style.DotSettings" \
          --output="${{ github.workspace }}/inspectCodeResults.xml" \
          --no-build \
          "${{ github.workspace }}/${{ env.PROJECT_SOLUTION }}"
    
    - name: Upload InspectCode Results
      uses: actions/upload-artifact@v4
      with:
        name: inspectcode-results
        path: ${{ github.workspace }}/${{ env.PROJECT_PATH }}/inspectCodeResults.xml
