name: Rider Code Style Check

on:
  workflow_dispatch:  # ручной запуск вручную через GitHub Actions

jobs:
  rider-style-check:
    runs-on: self-hosted  # твой self-hosted Mac агент

    env:
      PROJECT_PATH: static-analysis-project  # относительная папка проекта
      PROJECT_SOLUTION: static-analysis-project.sln # имя .sln файла проекта

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0.x'

    - name: Find Rider installation
      id: find_rider
      run: |
        RIDER_APP_PATH=$(find /Applications -name "Rider.app" | head -n 1)
        echo "RIDER_APP_PATH=$RIDER_APP_PATH" >> $GITHUB_ENV
        echo "Found Rider: $RIDER_APP_PATH"

    - name: Run Rider InspectCode
      run: |
        "$RIDER_APP_PATH/Contents/MacOS/rider" inspectcode \
          --profile="${{ github.workspace }}/${{ env.PROJECT_PATH }}/hitapps_style.DotSettings" \
          --output="${{ github.workspace }}/${{ env.PROJECT_PATH }}/inspectCodeResults.xml" \
          "${{ github.workspace }}/${{ env.PROJECT_PATH }}/${{ env.PROJECT_SOLUTION }}"

    - name: Upload InspectCode Results
      uses: actions/upload-artifact@v4
      with:
        name: inspectcode-results
        path: ${{ github.workspace }}/${{ env.PROJECT_PATH }}/inspectCodeResults.xml
