name: ReSharper Code Style Check with Comments

on:
  workflow_dispatch:

jobs:
  code-style-check:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0.x'

    - name: Download ReSharper CLI
      run: |
        wget https://download.jetbrains.com/resharper/ReSharperCommandLineTools.2025.1.2.zip
        unzip ReSharperCommandLineTools.2025.1.2.zip -d resharper-cli
        
    - name: Run InspectCode
      run: |
        mono ./resharper-cli/inspectcode.sh --profile=hitapps_style.DotSettings --output=inspectCodeResults.xml .

    - name: Parse InspectCode XML
      run: |
        python3 parse_inspectcode.py
